package com.example.spaceapp;

import java.util.ArrayList;
import java.util.List;

public class DataSourcePlanet {

    public static List<Planet> getPlanets() {
        List<Planet> planets = new ArrayList<>();
        planets.add(new Planet(R.drawable.earth,R.drawable.earth1,R.drawable.earth2,R.drawable.earth3,"Earth", "Bumi adalah satu-satunya planet yang diketahui memiliki kehidupan di Tata Surya kita. Ini memiliki atmosfer yang mendukung kehidupan dengan campuran gas-gas seperti nitrogen, oksigen, dan karbon dioksida. Bumi memiliki siklus air yang kompleks, pola iklim yang beragam, dan struktur dalam yang terdiri dari inti, mantel, dan kerak. Satelit alaminya adalah Bulan, dan medan magnetnya melindungi planet ini dari radiasi luar angkasa. Bumi juga kaya akan kehidupan laut dan darat, menawarkan beragam spesies yang mencakup hewan, tumbuhan, jamur, dan mikroba."));
        planets.add(new Planet(R.drawable.jupiter,R.drawable.jupiter1,R.drawable.jupiter2,R.drawable.jupiter3,"Jupiter","Jupiter adalah planet terbesar dalam Tata Surya kita dan merupakan salah satu dari dua planet gas raksasa, yang lainnya adalah Saturnus. Dikenal dengan ciri khasnya berupa gurun merah raksasa, yang sebenarnya adalah badai besar yang terus berputar di atmosfernya, Jupiter memiliki sistem cincin yang samar dan lebih dari 70 satelit alami, termasuk yang terbesar, Ganymede. Planet ini memiliki inti padat yang mungkin terdiri dari batuan dan logam, yang dikelilingi oleh lapisan atmosfer yang tebal dari hidrogen dan helium. Jupiter memiliki medan magnet yang sangat kuat, sehingga memanjangkan jaraknya jauh melampaui orbit planet ini. Selain itu, planet ini juga dikenal dengan Merah Raksasa Besar, badai yang telah berlangsung selama berabad-abad di atmosfernya."));
        planets.add(new Planet(R.drawable.mars,R.drawable.mars1,R.drawable.mars2,R.drawable.mars3,"Mars","Mars, yang juga dikenal sebagai (Planet Merah), adalah planet keempat dari Matahari dalam Tata Surya kita. Mars telah menarik perhatian manusia selama berabad-abad karena kemiripannya dengan Bumi dan potensi untuk mendukung kehidupan. Planet ini memiliki permukaan yang terdiri dari gurun, gunung berapi, lembah, dan gletser yang memberikan bukti aktivitas geologis yang beragam di masa lalu. Salah satu fitur paling mencolok adalah Gunung Olympus, gunung berapi tertinggi di Tata Surya, serta Lembah Marineris, lembah yang sangat besar dan dalam. Selain itu, Mars memiliki atmosfer yang tipis yang terutama terdiri dari karbon dioksida, serta dua bulan alami, Phobos dan Deimos."));
        planets.add(new Planet(R.drawable.merkurius,R.drawable.merkurius1,R.drawable.merkurius2,R.drawable.merkurius3,"Merkurius","Merkurius adalah planet terkecil dan terdekat dengan Matahari dalam Tata Surya kita. Dikenal karena orbitnya yang cepat dan permukaannya yang dipenuhi kawah, Merkurius menghadapi suhu yang ekstrem karena jaraknya yang dekat dengan Matahari. Permukaannya terdiri dari lanskap yang penuh dengan kawah dan ngarai, menunjukkan tanda-tanda aktivitas vulkanik masa lalu. Merkurius tidak memiliki atmosfer yang signifikan, sehingga tidak memiliki perlindungan dari radiasi Matahari yang keras. Salah satu fitur menariknya adalah pergerakan orbitalnya yang eksentrik, yang menghasilkan fenomena unik seperti efek pegas dan malam yang panjang di Merkurius."));
        planets.add(new Planet(R.drawable.neptunus,R.drawable.neptunus1,R.drawable.neptunus2,R.drawable.neptunus3,"Neptunus","Neptunus adalah planet terjauh dari Matahari dalam Tata Surya kita dan merupakan salah satu dari dua planet gas raksasa, bersama dengan Uranus. Dikenal karena warnanya yang biru dan atmosfer yang berawan, Neptunus memiliki sistem cincin dan banyak satelit alami yang mengorbitinya. Planet ini memiliki struktur internal yang mirip dengan Uranus, dengan inti yang mungkin terdiri dari batuan dan es, dikelilingi oleh lapisan atmosfer gas dan cairan. Salah satu fitur paling menarik dari Neptunus adalah kecepatan anginnya yang ekstrem di atmosfer atas, yang mencapai kecepatan lebih dari 2.100 kilometer per jam."));
        planets.add(new Planet(R.drawable.saturn,R.drawable.saturnus1,R.drawable.saturnus2,R.drawable.saturnus3,"Saturnus","Saturnus, planet gas raksasa keenam dari Matahari dalam Tata Surya kita, dikenal karena sistem cincinnya yang spektakuler yang terdiri dari ribuan gelombang cincin yang tipis. Planet ini memiliki komposisi utama hidrogen dan helium, dengan inti padat yang mungkin terdiri dari logam dan batuan di dalamnya. Selain itu, Saturnus memiliki magnetosfer yang kuat, lebih dari 80 satelit alami yang diketahui, dan periode rotasi yang lambat, menghasilkan fenomena visual runcing yang mencolok di antara planet lainnya. Misinya, seperti Cassini-Huygens, telah memberikan wawasan mendalam tentang karakteristik planet ini, menjadikannya objek penelitian yang menarik bagi ilmuwan."));
        planets.add(new Planet(R.drawable.uranus,R.drawable.uranus1,R.drawable.uranus2,R.drawable.uranus3,"Uranus","Uranus adalah salah satu planet gas raksasa dalam Tata Surya kita yang terletak di sekitar orbit yang lebih jauh dari Matahari daripada Saturnus dan Jupiter, tetapi lebih dekat dari Neptunus. Planet ini dikenal dengan sumbu rotasinya yang sangat miring, sehingga orbitnya hampir sejajar dengan bidang ekliptika Tata Surya. Uranus memiliki atmosfer yang terdiri dari hidrogen, helium, dan sedikit metana yang memberikan warna biru-kehijauan khas pada planet ini. Salah satu fitur menarik dari Uranus adalah keberadaan cincinnya yang halus dan 27 satelit alaminya, termasuk Miranda, yang memiliki topografi yang penuh dengan ngarai dan gunung yang sangat ekstrem. Misi seperti Voyager 2 telah memberikan wawasan mendalam tentang Uranus. "));
        planets.add(new Planet(R.drawable.venus,R.drawable.venus1,R.drawable.venus2,R.drawable.venus3,"Venus","Venus, sering disebut sebagai (planet kembar) Bumi karena ukurannya yang hampir sama, adalah planet kedua dari Matahari dalam Tata Surya kita. Namun, perbedaan dramatis terletak pada kondisi permukaannya yang sangat berbeda. Venus memiliki atmosfer yang tebal yang terutama terdiri dari karbon dioksida dengan awan tebal asam sulfur dioksida, menciptakan efek rumah kaca yang kuat dan menyebabkan suhu permukaan yang sangat tinggi, menjadikannya planet terpanas di Tata Surya. Permukaannya dipenuhi dengan dataran yang luas dan kawah-kawah besar akibat aktivitas vulkanik yang intensif. Venus juga memiliki rotasi yang lambat dan berlawanan arah jarum jam, sehingga satu hari Venus lebih panjang dari satu tahun Venus."));
        // Add more planets as needed
        return planets;
    }
}
